### PR TITLE
Add basic support for PostgreSQL 9.3.

### PR DESCRIPTION
**Pull request by schmiddy**
I noticed compiler warnings crept up for this module when building against PostgreSQL 9.3 or 9.3, complaining about:

plpgsql_lint.c:1361:4: warning: implicit declaration of function ‘heap_freetuple’ [-Wimplicit-function-declaration]

due to the reorganization of htup.h into htup_details.h. Also, there was no 'make check' support for 9.3. Fixed these issues, plpgsql_lint seems to work OK on 9.3 now.

### CODE REVIEW

**Comment by okbob** [comment]
A event triggers support is missing still
